<?php

/**
 * @file
 * Primary module hooks for countdown_flipclock module.
 */

/**
 * Implements hook_theme().
 */
function countdown_flipclock_theme($existing, $type, $theme, $path):array {
  return [
    'countdown_flipclock' => [
      'variables' => [
        'title' => NULL,
        'target_datetime' => NULL,
        'units' => [],
      ],
      'template' => 'countdown-flipclock',
    ],
  ];
}
